name: example
description: >
  Displays an About dialog, which describes the application,
  can show licenses, changelog, and other information.
version: 1.0.0+3
_author: David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/flutter_about

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  about:
  cupertino_icons:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  pubspec_extract:

dependency_overrides:
  about:
    path: ..

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.md
    - README.md

builders:
  about:
